# Generated by Django 6.0.6 on 2026-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('attendance', models.FloatField()),
            ],
        ),
    ]
